### ISSUE TITLE
Missing name space

### ISSUE THREAD

**Issue by Ianchandler1990** [PureGero/SchemToSchematic#2]
Unknown namespace key: minecraft:grass_block, replacing with air.
Unknown namespace key: minecraft:iron_trapdoor, replacing with air.
Unknown namespace key: minecraft:jungle_leaves, replacing with air.
Unknown namespace key: minecraft:spruce_door, replacing with air.
Unknown namespace key: minecraft:stone_brick_stairs, replacing with air.
Unknown namespace key: minecraft:black_stained_glass_pane, replacing with air.
Unknown namespace key: minecraft:gray_stained_glass_pane, replacing with air.
Unknown namespace key: minecraft:oak_fence, replacing with air.
Unknown namespace key: minecraft:white_stained_glass_pane, replacing with air.
Unknown namespace key: minecraft:lantern, replacing with air.
Unknown namespace key: minecraft:smooth_stone_slab, replacing with air.

**Comment by PureGero** [comment]
What program was used to create the .schem file?

**Comment by ikuria** [comment]
Unknown namespace key: minecraft:basalt[axis=z], replacing with air.
Unknown namespace key: minecraft:andesite_stairs[facing=east,half=bottom,shape=straight,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:basalt[axis=y], replacing with air.
Unknown namespace key: minecraft:seagrass, replacing with air.
Unknown namespace key: minecraft:mossy_cobblestone_slab[type=double,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:mossy_cobblestone_slab[type=bottom,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:dark_oak_button[face=floor,facing=east,powered=false], replacing with air.
Unknown namespace key: minecraft:basalt[axis=x], replacing with air.
Unknown namespace key: minecraft:andesite_stairs[facing=north,half=bottom,shape=straight,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:dead_horn_coral_fan[waterlogged=false], replacing with air.
Unknown namespace key: minecraft:dead_fire_coral[waterlogged=false], replacing with air.
Unknown namespace key: minecraft:stone_brick_wall[east=none,north=none,south=low,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:stone_brick_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=low], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=low], replacing with air.
Unknown namespace key: minecraft:polished_basalt[axis=y], replacing with air.
Unknown namespace key: minecraft:moss_carpet, replacing with air.
Unknown namespace key: minecraft:sea_pickle[pickles=2,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:blue_ice, replacing with air.
Unknown namespace key: minecraft:stripped_oak_log[axis=y], replacing with air.
Unknown namespace key: minecraft:stone_brick_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:stripped_oak_log[axis=z], replacing with air.
Unknown namespace key: minecraft:stripped_oak_log[axis=x], replacing with air.
Unknown namespace key: minecraft:stripped_spruce_log[axis=y], replacing with air.
Unknown namespace key: minecraft:stone_brick_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_wall[east=tall,north=none,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=tall], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_wall[east=low,north=none,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:stone_brick_wall[east=none,north=low,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:lantern[hanging=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_wall[east=none,north=none,south=tall,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:stone_brick_wall[east=tall,north=none,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:stone_brick_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=tall], replacing with air.
Unknown namespace key: minecraft:stone_brick_wall[east=none,north=tall,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=north,half=top,open=true,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=west,half=top,open=true,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=east,half=top,open=true,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=south,half=top,open=true,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=west,half=top,open=false,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=east,half=top,open=false,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:andesite_wall[east=none,north=none,south=none,up=true,waterlogged=false,west=none], replacing with air.
Unknown namespace key: minecraft:candle[candles=3,lit=true,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_stairs[facing=south,half=top,shape=straight,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_stairs[facing=east,half=top,shape=straight,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_stairs[facing=west,half=top,shape=straight,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:mossy_stone_brick_stairs[facing=north,half=top,shape=straight,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=south,half=top,open=false,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=west,half=bottom,open=false,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=east,half=bottom,open=false,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:polished_blackstone_button[face=floor,facing=north,powered=false], replacing with air.
Unknown namespace key: minecraft:polished_blackstone_button[face=floor,facing=east,powered=false], replacing with air.
Unknown namespace key: minecraft:spruce_trapdoor[facing=north,half=top,open=false,powered=false,waterlogged=false], replacing with air.
Unknown namespace key: minecraft:bell[attachment=ceiling,facing=north,powered=false], replacing with air.

**Comment by ikuria** [comment]
how do you know the value number?

**Comment by PureGero** [comment]
@ikuria Unfortunately .schematic files are for versions of Minecraft ≤ 1.12, 1.13 through to 1.17 blocks like the ones you've attached simply can't exist in .schematic files.

**Comment by PureGero** [comment]
Closing due to lack of response
