### ISSUE TITLE
All non full blocks turn to air

### ISSUE THREAD

**Issue by itsWarHammer** [PureGero/SchemToSchematic#3]
Iron bars redstone stairs slabs and everything that isnt a full block is turned to air after using this amazing tool!

**Comment by itsWarHammer** [comment]
1.16 FAWE used to create .schem

**Comment by PureGero** [comment]
Can confirm this is an issue with FAWE.
I've create an issue with them about this: IntellectualSites/FastAsyncWorldEdit#1052 
Until it's fixed, I recommend using WorldEdit to create the schematics for use with this tool

**Comment by PureGero** [comment]
This has now been fixed, update to at least FAWE version 670.
