### ISSUE TITLE
1.16 update

### ISSUE THREAD

**Issue by Loliver-dot** [PureGero/SchemToSchematic#4]
Is there a way that I can upgrade your files so I can use this for some 1.16 blocks or is that impossible? I tried to add the few blocks I needed inside the list in schemtoschematic.js. There where no errors but when loaded the new blocks wheren´t there.

**Comment by PureGero** [comment]
Unfortunately .schematic files are for versions of Minecraft ≤ 1.12, 1.16 blocks simply can't exist in .schematic files.
